import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Section from '../components/Section';
import ContactForm from '../components/ContactForm';
import Model from '../components/Model';

export default function Home() {
  return (
    <>
      <Head>
      
        <title>My Portfolio</title> 
        <meta name="description" content="Generated by create next app" /> 
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
      {/* Основной контент страницы */}
      <main className="bg-gray-100 min-h-screen"> 
      {/* Заголовок сайта */}
        <Header /> 
        {/* Секция "About Me" */}
        <Section title="About Me"> 
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
            tincidunt, eros et ultricies dignissim, sem quam blandit lectus, id
            fringilla libero est eu nibh. Donec eu libero vel augue fermentum
            iaculis.
          </p>
        </Section>
         {/* Секция "My Work" */}
        <Section title="My Work"> 
          <Model />
        </Section>
         {/* Секция "Contact Me" */}
        <Section title="Contact Me"> 
          <ContactForm />
        </Section>
         {/* Футер сайта */}
        <Footer /> 
      </main>
    </>
  );
}
