import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
import { motion, useAnimation, useInView } from 'framer-motion'; // Импорт хуков Framer Motion для управления анимацией
import { gsap } from 'gsap'; // Импорт библиотеки GSAP для создания сложных анимаций
import Header from '../components/Header';
import Footer from '../components/Footer';
import Section from '../components/Section';
import ContactForm from '../components/ContactForm';
import Model from '../components/Model';




export default function Home() {
  const ref = useRef<HTMLDivElement>(null); // Ссылка на DOM-элемент, который будет содержать секцию "My Work"
  const inView = useInView(); // Хук useInView для определения видимости секции
  const animation = useAnimation(); // Хук useAnimation для управления анимацией секции

  useEffect(() => { // Хук useEffect, который запускается, когда секция становится видимой или невидимой
    if (inView) { // Если секция видна
      gsap.to(animation, { // Анимация появления секции с помощью GSAP
        opacity: 1, // Конечная прозрачность: 1 (видимый)
        x: 0, // Конечное положение по оси X: 0 (без смещения)
        duration: 1, // Длительность анимации: 1 секунда
        ease: 'power3.inOut', // Тип анимации: плавная
      });
    } else { // Если секция не видна
      gsap.to(animation, { // Анимация скрытия секции с помощью GSAP
        opacity: 0, // Конечная прозрачность: 0 (невидимый)
        x: -50, // Конечное положение по оси X: -50 пикселей (смещение за экран)
        duration: 1, // Длительность анимации: 1 секунда
        ease: 'power3.inOut', // Тип анимации: плавная
      });
    }
  }, [inView, animation]); // Зависимости хука: inView и animation

  return (
    <>
      <Head>
        <title>My Portfolio</title> 
        <meta name="description" content="Generated by create next app" /> 
        <link rel="icon" href="/favicon.ico" /> 
      </Head>
       {/* Основной контент страницы */}
      <main className="bg-gray-100 min-h-screen"> 
       {/* Заголовок сайта */}
        <Header /> 
         {/* Секция "About Me" */}
        <Section title="About Me"> 
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
            tincidunt, eros et ultricies dignissim, sem quam blandit lectus, id
            fringilla libero est eu nibh. Donec eu libero vel augue fermentum
            iaculis.
          </p>
        </Section>

        {/* Анимированный контейнер для секции "My Work" */}
        <motion.div
          ref={ref} // Установка ссылки на DOM-элемент
          animate={animation} // Анимация: visible, если секция видна
          initial={{ opacity: 0, x: -50 }} // Начальное состояние: непрозрачный, смещен за экран
          transition={{ duration: 1, ease: 'power3.inOut' }} // Тип анимации: плавная
        >
          {/*  Секция "My Work" */}
          <Section title="My Work"> 
            <Model />
          </Section>
        </motion.div>
         {/* Секция "Contact Me" */}
        <Section title="Contact Me"> 
          <ContactForm />
        </Section>

        <Footer /> 
      </main>
    </>
  );
}
